issues:
    default_status: ready
    default_type: task
    path: .issues
sync:
    clickup:
        custom_fields:
            bean_id: a0b0c69a-d036-4031-9deb-4ecc4cfa3e55
            created_at: d3adc5e1-eedf-46e0-b5d5-a4dce3a0666b
        list_id: "901112937048"
        status_mapping:
            completed: completed
            draft: not started
            in-progress: in progress
            ready: not started
            scrapped: completed
        type_mapping:
            bug: 1001
            epic: 1002
            feature: 0
            milestone: 1
            task: 0
