// Code generated by cmd/generate-data; DO NOT EDIT.

package data

//nolint:dupword
var MediaFeatures = []MediaFeature{
	{
		Name:        "any-hover",
		Description: "The any-hover CSS media feature can be used to test whether any available input mechanism can hover over elements.",
		Type:        "discrete",
		Values:      []string{"none", "hover"},
	},
	{
		Name:        "any-pointer",
		Description: "The any-pointer CSS media feature tests whether the user has any pointing device (such as a mouse), and if so, how accurate it is.",
		Type:        "discrete",
		Values:      []string{"none", "coarse", "fine"},
	},
	{
		Name:        "aspect-ratio",
		Description: "The aspect-ratio CSS media feature can be used to test the aspect ratio of the viewport.",
		Type:        "range",
	},
	{
		Name:        "color",
		Description: "The color CSS media feature can be used to test the number of bits per color component (red, green, blue) of the output device.",
		Type:        "range",
	},
	{
		Name:        "color-gamut",
		Description: "The color-gamut CSS media feature is used to apply CSS styles based on the approximate range of color gamut supported by the user agent and the output device.",
		Type:        "discrete",
		Values:      []string{"srgb", "p3", "rec2020"},
	},
	{
		Name:        "color-index",
		Description: "The color-index CSS media feature can be used to test the number of entries in the output device's color lookup table.",
		Type:        "range",
	},
	{
		Name:        "device-aspect-ratio",
		Description: "The device-aspect-ratio CSS media feature can be used to test the width-to-height aspect ratio of an output device.",
		Type:        "range",
	},
	{
		Name:        "device-height",
		Description: "The device-height CSS media feature can be used to test the height of an output device's rendering surface.",
		Type:        "range",
	},
	{
		Name:        "device-width",
		Description: "The device-width CSS media feature can be used to test the width of an output device's rendering surface.",
		Type:        "range",
	},
	{
		Name:        "display-mode",
		Description: "The display-mode CSS media feature can be used to test whether a web app is being displayed in a normal browser tab or in some alternative way, such as a standalone app or fullscreen mode.",
		Type:        "discrete",
		Values:      []string{"fullscreen", "standalone", "minimal-ui", "browser", "picture-in-picture"},
	},
	{
		Name:        "dynamic-range",
		Description: "The dynamic-range CSS media feature can be used to test the combination of brightness, contrast ratio, and color depth that are supported by the user agent and the output device.",
		Type:        "discrete",
		Values:      []string{"standard", "high"},
	},
	{
		Name:   "environment-blending",
		Type:   "discrete",
		Values: []string{"opaque", "additive", "subtractive"},
	},
	{
		Name:        "forced-colors",
		Description: "The forced-colors CSS media feature is used to detect if the user agent has enabled a forced colors mode where it enforces a user-chosen limited color palette on the page. An example of a forced colors mode is Windows High Contrast mode.",
		Type:        "discrete",
		Values:      []string{"none", "active"},
	},
	{
		Name:        "grid",
		Description: "The grid CSS media feature can be used to test whether the output device uses a grid-based screen.",
		Type:        "discrete",
	},
	{
		Name:        "height",
		Description: "The height CSS media feature can be used to apply styles based on the height of the viewport (or the page box, for paged media).",
		Type:        "range",
	},
	{
		Name:        "horizontal-viewport-segments",
		Description: "Detects whether the device has a specified number of viewport segments laid out horizontally (side by side).",
		Type:        "range",
	},
	{
		Name:        "hover",
		Description: "The hover CSS media feature can be used to test whether the user's primary input mechanism can hover over elements.",
		Type:        "discrete",
		Values:      []string{"none", "hover"},
	},
	{
		Name:        "inverted-colors",
		Description: "The inverted-colors CSS media feature is used to test if the user agent or the underlying operating system has inverted all colors.",
		Type:        "discrete",
		Values:      []string{"none", "inverted"},
	},
	{
		Name:        "monochrome",
		Description: "The monochrome CSS media feature can be used to test the number of bits per pixel in the monochrome frame buffer of the output device.",
		Type:        "range",
	},
	{
		Name:   "nav-controls",
		Type:   "discrete",
		Values: []string{"none", "back"},
	},
	{
		Name:        "orientation",
		Description: "The orientation CSS media feature can be used to test the orientation of the viewport (or the page box, for paged media).",
		Type:        "discrete",
		Values:      []string{"portrait", "landscape"},
	},
	{
		Name:        "overflow-block",
		Description: "The overflow-block CSS media feature can be used to test how the output device handles content that overflows the initial containing block along the block axis.",
		Type:        "discrete",
		Values:      []string{"none", "scroll", "paged"},
	},
	{
		Name:        "overflow-inline",
		Description: "The overflow-inline CSS media feature can be used to test how the output device handles content that overflows the initial containing block along the inline axis.",
		Type:        "discrete",
		Values:      []string{"none", "scroll"},
	},
	{
		Name:        "pointer",
		Description: "The pointer CSS media feature tests whether the user has a pointing device (such as a mouse), and if so, how accurate the primary pointing device is.",
		Type:        "discrete",
		Values:      []string{"none", "coarse", "fine"},
	},
	{
		Name:        "prefers-color-scheme",
		Description: "The prefers-color-scheme CSS media feature is used to detect if a user has requested light or dark color themes.",
		Type:        "discrete",
		Values:      []string{"light", "dark"},
	},
	{
		Name:        "prefers-contrast",
		Description: "The prefers-contrast CSS media feature is used to detect whether the user has requested the web content to be presented with a lower or higher contrast.",
		Type:        "discrete",
		Values:      []string{"no-preference", "less", "more", "custom"},
	},
	{
		Name:        "prefers-reduced-data",
		Description: "The prefers-reduced-data CSS media feature is used to detect if the user has requested the web content that consumes less internet traffic.",
		Type:        "discrete",
		Values:      []string{"no-preference", "reduce"},
	},
	{
		Name:        "prefers-reduced-motion",
		Description: "The prefers-reduced-motion CSS media feature is used to detect if a user has enabled a setting on their device to minimize the amount of non-essential motion. The setting is used to convey to the browser on the device that the user prefers an interface that removes, reduces, or replaces motion-based animations.",
		Type:        "discrete",
		Values:      []string{"no-preference", "reduce"},
	},
	{
		Name:        "prefers-reduced-transparency",
		Description: "The prefers-reduced-transparency CSS media feature is used to detect if a user has enabled a setting on their device to reduce the transparent or translucent layer effects used on the device. Switching on such a setting can help improve contrast and readability for some users.",
		Type:        "discrete",
		Values:      []string{"no-preference", "reduce"},
	},
	{
		Name:        "resolution",
		Description: "The resolution CSS media feature can be used to test the pixel density of the output device.",
		Type:        "range",
	},
	{
		Name:        "scan",
		Description: "The scan CSS media feature is used to apply CSS styles based on the scanning process of the output device.",
		Type:        "discrete",
		Values:      []string{"interlace", "progressive"},
	},
	{
		Name:        "scripting",
		Description: "The scripting CSS media feature can be used to test whether scripting (such as JavaScript) is available.",
		Type:        "discrete",
		Values:      []string{"none", "initial-only", "enabled"},
	},
	{
		Name:        "shape",
		Description: "The shape CSS media feature can be used to test the shape of the device to distinguish rectangular and round displays.",
		Type:        "discrete",
		Values:      []string{"rect", "round"},
	},
	{
		Name:        "update",
		Description: "The update CSS media feature can be used to test how frequently (if at all) the output device is able to modify the appearance of content once rendered.",
		Type:        "discrete",
		Values:      []string{"none", "slow", "fast"},
	},
	{
		Name:        "vertical-viewport-segments",
		Description: "Detects whether the device has a specified number of viewport segments laid out vertically (top to bottom)",
		Type:        "range",
	},
	{
		Name:   "video-color-gamut",
		Type:   "discrete",
		Values: []string{"srgb", "p3", "rec2020"},
	},
	{
		Name:        "video-dynamic-range",
		Description: "The video-dynamic-range CSS media feature can be used to test the combination of brightness, contrast ratio, and color depth that are supported by the video plane of the user agent and the output device.",
		Type:        "discrete",
		Values:      []string{"standard", "high"},
	},
	{
		Name:        "width",
		Description: "The width CSS media feature can be used to test the width of the viewport (or the page box, for paged media).",
		Type:        "range",
	},
}

var mediaFeatureMap = buildMediaFeatureMap()

func buildMediaFeatureMap() map[string]MediaFeature {
	m := make(map[string]MediaFeature, len(MediaFeatures))
	for _, f := range MediaFeatures {
		m[f.Name] = f
	}
	return m
}
