// Code generated by cmd/generate-data; DO NOT EDIT.

package data

// PseudoClasses contains definitions for CSS pseudo-classes.
var PseudoClasses = []PseudoClass{
	{
		Name:        "active",
		Description: "Applies while an element is being activated by the user. For example, between the times the user presses the mouse button and releases it.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "active-view-transition",
		Description: "Matches the root element of a document when a view transition is in progress (active) and stops matching once the transition has completed.",
		Baseline:    Baseline{Status: "low", LowDate: "2025-10-14"},
	},
	{
		Name:     "active-view-transition-type",
		Baseline: Baseline{Status: "false"},
	},
	{
		Name:        "any-link",
		Description: "Represents an element that acts as the source anchor of a hyperlink. Applies to both visited and unvisited links.",
		Baseline:    Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name:        "autofill",
		Description: "The :autofill CSS pseudo-class matches when an input element has its value autofilled by the browser. The class stops matching if the user edits the field.",
		Baseline:    Baseline{Status: "high", LowDate: "2023-02-09", HighDate: "2025-08-09"},
	},
	{
		Name:        "blank",
		Description: "The :blank CSS pseudo-class selects empty user input elements (eg. <input> or <textarea>).",
		StatusInfo:  StatusInfo{Status: "experimental"},
	},
	{
		Name:        "buffering",
		Description: "The :buffering CSS pseudo-class selector represents an element that is playable, such as audio or video, when the playable element is buffering a media resource.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "checked",
		Description: "Radio and checkbox elements can be toggled by the user. Some menu items are 'checked' when the user selects them. When such elements are toggled 'on' the :checked pseudo-class applies.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "corner-present",
		Description: "Non-standard. Indicates whether or not a scrollbar corner is present.",
	},
	{
		Name:        "current",
		Description: "The :current CSS pseudo-class selector is a time-dimensional pseudo-class that represents the element, or an ancestor of the element, that is currently being displayed",
		StatusInfo:  StatusInfo{Status: "experimental"},
	},
	{
		Name:        "decrement",
		Description: "Non-standard. Applies to buttons and track pieces. Indicates whether or not the button or track piece will decrement the view's position when used.",
	},
	{
		Name:        "default",
		Description: "Applies to the one or more UI elements that are the default among a set of similar elements. Typically applies to context menu items, buttons, and select lists/menus.",
		Baseline:    Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name:        "defined",
		Description: "The :defined CSS pseudo-class represents any element that has been defined. This includes any standard element built in to the browser, and custom elements that have been successfully defined (i.e. with the CustomElementRegistry.define() method).",
		Baseline:    Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name:        "dir",
		Description: "The :dir() CSS pseudo-class matches elements based on the directionality of the text contained in them.",
		Baseline:    Baseline{Status: "low", LowDate: "2023-12-07"},
	},
	{
		Name:        "disabled",
		Description: "Represents user interface elements that are in a disabled state; such elements have a corresponding enabled state.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "double-button",
		Description: "Non-standard. Applies to buttons and track pieces. Applies when both buttons are displayed together at the same end of the scrollbar.",
	},
	{
		Name:        "empty",
		Description: "Represents an element that has no children at all.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "enabled",
		Description: "Represents user interface elements that are in an enabled state; such elements have a corresponding disabled state.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "end",
		Description: "Non-standard. Applies to buttons and track pieces. Indicates whether the object is placed after the thumb.",
	},
	{
		Name:        "first",
		Description: "When printing double-sided documents, the page boxes on left and right pages may be different. This can be expressed through CSS pseudo-classes defined in the  page context.",
		Baseline:    Baseline{Status: "low", LowDate: "2023-08-01"},
	},
	{
		Name:        "first-child",
		Description: "Same as :nth-child(1). Represents an element that is the first child of some other element.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "first-of-type",
		Description: "Same as :nth-of-type(1). Represents an element that is the first sibling of its type in the list of children of its parent element.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "focus",
		Description: "Applies while an element has the focus (accepts keyboard or mouse events, or other forms of input).",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "focus-visible",
		Description: "The :focus-visible pseudo-class applies while an element matches the :focus pseudo-class and the UA determines via heuristics that the focus should be made evident on the element.",
		Baseline:    Baseline{Status: "high", LowDate: "2022-03-14", HighDate: "2024-09-14"},
	},
	{
		Name:        "focus-within",
		Description: "The :focus-within pseudo-class applies to any element for which the :focus pseudo class applies as well as to an element whose descendant in the flat tree (including non-element nodes, such as text nodes) matches the conditions for matching :focus.",
		Baseline:    Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name:        "fullscreen",
		Description: "Matches any element that has its fullscreen flag set.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "future",
		Description: "Represents any element that is defined to occur entirely after a :current element.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "has",
		Description: "The functional :has() CSS pseudo-class represents an element if any of the relative selectors that are passed as an argument match at least one element when anchored against this element. ",
		Baseline:    Baseline{Status: "low", LowDate: "2023-12-19"},
	},
	{
		Name:        "has-slotted",
		Description: "The :has-slotted CSS pseudo-class matches when the content of a slot element is not empty or not using the default value (see Using templates and slots for more information).",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "horizontal",
		Description: "Non-standard. Applies to any scrollbar pieces that have a horizontal orientation.",
	},
	{
		Name:        "host",
		Description: "When evaluated in the context of a shadow tree, it matches the shadow tree's host element if the host element, in its normal context, matches the selector argument.",
		Baseline:    Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name:        "host",
		Description: "When evaluated in the context of a shadow tree, matches the shadow tree's host element.",
		Baseline:    Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name:        "host-context",
		Description: "Tests whether there is an ancestor, outside the shadow tree, which matches a particular selector.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "hover",
		Description: "Applies while the user designates an element with a pointing device, but does not necessarily activate it. For example, a visual user agent could apply this pseudo-class when the cursor (mouse pointer) hovers over a box generated by the element.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "in-range",
		Description: "Used in conjunction with the min and max attributes, whether on a range input, a number field, or any other types that accept those attributes.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-11-12", HighDate: "2018-05-12"},
	},
	{
		Name:        "increment",
		Description: "Non-standard. Applies to buttons and track pieces. Indicates whether or not the button or track piece will increment the view's position when used.",
	},
	{
		Name:        "indeterminate",
		Description: "Applies to UI elements whose value is in an indeterminate state.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "invalid",
		Description: "An element is :valid or :invalid when it is, respectively, valid or invalid with respect to data validity semantics defined by a different specification.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "is",
		Description: "The :is() CSS pseudo-class function takes a selector list as its argument, and selects any element that can be selected by one of the selectors in that list. This is useful for writing large selectors in a more compact form.",
		Baseline:    Baseline{Status: "high", LowDate: "2021-01-21", HighDate: "2023-07-21"},
	},
	{
		Name:        "lang",
		Description: "Represents an element that is in language specified.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "last-child",
		Description: "Same as :nth-last-child(1). Represents an element that is the last child of some other element.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "last-of-type",
		Description: "Same as :nth-last-of-type(1). Represents an element that is the last sibling of its type in the list of children of its parent element.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "left",
		Description: "When printing double-sided documents, the page boxes on left and right pages may be different. This can be expressed through CSS pseudo-classes defined in the  page context.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "link",
		Description: "Applies to links that have not yet been visited.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "local-link",
		Description: "The :local-link CSS pseudo-class represents an link to the same document",
		StatusInfo:  StatusInfo{Status: "experimental"},
	},
	{
		Name:        "matches",
		Description: "Takes a selector list as its argument. It represents an element that is represented by its argument.",
	},
	{
		Name:        "modal",
		Description: "The :modal CSS pseudo-class matches an element that is in a state in which it excludes all interaction with elements outside it until the interaction has been dismissed. Multiple elements can be selected by the :modal pseudo-class at the same time, but only one of them will be active and able to receive input.",
		Baseline:    Baseline{Status: "high", LowDate: "2022-09-02", HighDate: "2025-03-02"},
	},
	{
		Name:        "muted",
		Description: "The :muted CSS pseudo-class selector represents an element that is capable of making sound, such as audio or video, but is muted (forced silent).",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "no-button",
		Description: "Non-standard. Applies to track pieces. Applies when there is no button at that end of the track.",
	},
	{
		Name:        "not",
		Description: "The negation pseudo-class, :not(X), is a functional notation taking a simple selector (excluding the negation pseudo-class itself) as an argument. It represents an element that is not represented by its argument.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "nth-child",
		Description: "Represents an element that has an+b-1 siblings before it in the document tree, for any positive integer or zero value of n, and has a parent element.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "nth-last-child",
		Description: "Represents an element that has an+b-1 siblings after it in the document tree, for any positive integer or zero value of n, and has a parent element.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "nth-last-of-type",
		Description: "Represents an element that has an+b-1 siblings with the same expanded element name after it in the document tree, for any zero or positive integer value of n, and has a parent element.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "nth-of-type",
		Description: "Represents an element that has an+b-1 siblings with the same expanded element name before it in the document tree, for any zero or positive integer value of n, and has a parent element.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "only-child",
		Description: "Represents an element that has a parent element and whose parent element has no other element children. Same as :first-child:last-child or :nth-child(1):nth-last-child(1), but with a lower specificity.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "only-of-type",
		Description: "Matches every element that is the only child of its type, of its parent. Same as :first-of-type:last-of-type or :nth-of-type(1):nth-last-of-type(1), but with a lower specificity.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "open",
		Description: "The :open CSS pseudo-class represents an element that has open and closed states, only when it is currently in the open state.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "optional",
		Description: "A form element is :required or :optional if a value for it is, respectively, required or optional before the form it belongs to is submitted. Elements that are not form elements are neither required nor optional.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "out-of-range",
		Description: "Used in conjunction with the min and max attributes, whether on a range input, a number field, or any other types that accept those attributes.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-11-12", HighDate: "2018-05-12"},
	},
	{
		Name:        "past",
		Description: "Represents any element that is defined to occur entirely prior to a :current element.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "paused",
		Description: "The :paused CSS pseudo-class selector is a resource state pseudo-class that will match an audio, video, or similar resource that is capable of being “played” or “paused”, when that element is “paused”.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "picture-in-picture",
		Description: "The :picture-in-picture CSS pseudo-class matches the element which is currently in picture-in-picture mode.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "placeholder-shown",
		Description: "The :placeholder-shown CSS pseudo-class represents any <input> or <textarea> element that is currently displaying placeholder text.",
		Baseline:    Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name:        "playing",
		Description: "The :playing CSS pseudo-class selector is a resource state pseudo-class that will match an audio, video, or similar resource that is capable of being “played” or “paused”, when that element is “playing”. ",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "popover-open",
		Description: "The :popover-open CSS pseudo-class represents a {{domxref(\"Popover API\", \"popover\", \"\", \"nocode\")}} element (i.e. one with a popover attribute) that is in the showing state. You can use this to apply style to popover elements only when they are shown.",
		Baseline:    Baseline{Status: "low", LowDate: "2024-04-16"},
	},
	{
		Name:        "read-only",
		Description: "An element whose contents are not user-alterable is :read-only. However, elements whose contents are user-alterable (such as text input fields) are considered to be in a :read-write state. In typical documents, most elements are :read-only.",
		Baseline:    Baseline{Status: "high", LowDate: "2020-07-28", HighDate: "2023-01-28"},
	},
	{
		Name:        "read-write",
		Description: "An element whose contents are not user-alterable is :read-only. However, elements whose contents are user-alterable (such as text input fields) are considered to be in a :read-write state. In typical documents, most elements are :read-only.",
		Baseline:    Baseline{Status: "high", LowDate: "2020-07-28", HighDate: "2023-01-28"},
	},
	{
		Name:        "required",
		Description: "A form element is :required or :optional if a value for it is, respectively, required or optional before the form it belongs to is submitted. Elements that are not form elements are neither required nor optional.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "right",
		Description: "When printing double-sided documents, the page boxes on left and right pages may be different. This can be expressed through CSS pseudo-classes defined in the  page context.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "root",
		Description: "Represents an element that is the root of the document. In HTML 4, this is always the HTML element.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "scope",
		Description: "Represents any element that is in the contextual reference element set.",
		Baseline:    Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name:        "seeking",
		Description: "The :seeking CSS pseudo-class selector represents an element that is playable, such as audio or video, when the playable element is seeking a playback position in the media resource.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "single-button",
		Description: "Non-standard. Applies to buttons and track pieces. Applies when both buttons are displayed separately at either end of the scrollbar.",
	},
	{
		Name:        "stalled",
		Description: "The :stalled CSS pseudo-class selector represents an element that is playable, such as audio or video, when playback is stalled.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "start",
		Description: "Non-standard. Applies to buttons and track pieces. Indicates whether the object is placed before the thumb.",
	},
	{
		Name:        "state",
		Description: "The :state() CSS pseudo-class matches custom elements that have the specified custom state.",
		Baseline:    Baseline{Status: "low", LowDate: "2024-05-17"},
	},
	{
		Name:        "target",
		Description: "Some URIs refer to a location within a resource. This kind of URI ends with a 'number sign' (#) followed by an anchor identifier (called the fragment identifier).",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "target-current",
		Description: "The :target-current CSS pseudo-class selects the active scroll marker — the ::scroll-marker pseudo-element of a scroll-marker-group that is currently scrolled to. This selector can be used to style the active navigation position within a scroll marker group.",
		StatusInfo:  StatusInfo{Status: "experimental"},
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "target-within",
		Description: "The :target-within CSS pseudo-class represents an element that is a target element or contains an element that is a target. A target element is a unique element with an id matching the URL's fragment.",
		StatusInfo:  StatusInfo{Status: "experimental"},
	},
	{
		Name:        "user-invalid",
		Description: "The :user-invalid CSS pseudo-class represents any validated form element whose value isn't valid based on their validation constraints, after the user has interacted with it.",
		Baseline:    Baseline{Status: "low", LowDate: "2023-11-02"},
	},
	{
		Name:        "user-valid",
		Description: "The :user-valid CSS pseudo-class represents any validated form element whose value validates correctly based on its validation constraints. However, unlike :valid it only matches once the user has interacted with it.",
		Baseline:    Baseline{Status: "low", LowDate: "2023-11-02"},
	},
	{
		Name:        "valid",
		Description: "An element is :valid or :invalid when it is, respectively, valid or invalid with respect to data validity semantics defined by a different specification.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "vertical",
		Description: "Non-standard. Applies to any scrollbar pieces that have a vertical orientation.",
	},
	{
		Name:        "visited",
		Description: "Applies once the link has been visited by the user.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "volume-locked",
		Description: "The :volume-locked CSS pseudo-class selector represents an element that is capable of making sound, such as audio or video, but the audio volume of the media element is currently \"locked\" by the user.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "where",
		Description: "The :where() CSS pseudo-class function takes a selector list as its argument, and selects any element that can be selected by one of the selectors in that list.",
		Baseline:    Baseline{Status: "high", LowDate: "2021-01-21", HighDate: "2023-07-21"},
	},
	{
		Name:        "window-inactive",
		Description: "Non-standard. Applies to all scrollbar pieces. Indicates whether or not the window containing the scrollbar is currently active.",
	},
	{
		Name:       "xr-overlay",
		StatusInfo: StatusInfo{Status: "experimental"},
		Baseline:   Baseline{Status: "false"},
	},
}

// PseudoElements contains definitions for CSS pseudo-elements.
var PseudoElements = []PseudoElement{
	{
		Name:        "after",
		Description: "Represents a styleable child pseudo-element immediately after the originating element's actual content.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "backdrop",
		Description: "Used to create a backdrop that hides the underlying document for an element in a top layer (such as an element that is displayed fullscreen).",
		Baseline:    Baseline{Status: "high", LowDate: "2022-03-14", HighDate: "2024-09-14"},
	},
	{
		Name:        "before",
		Description: "Represents a styleable child pseudo-element immediately before the originating element's actual content.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "checkmark",
		Description: "The ::checkmark CSS pseudo-element targets the checkmark placed inside the currently-selected option element of a customizable select element. It can be used to provide a visual indication of which option is selected.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "content",
		Description: "Deprecated. Matches the distribution list itself, on elements that have one. Use ::slotted for forward compatibility.",
	},
	{
		Name:     "cue",
		Baseline: Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name:     "cue",
		Baseline: Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name: "cue-region",
	},
	{
		Name: "cue-region",
	},
	{
		Name:        "details-content",
		Description: "The ::details-content CSS pseudo-element represents the expandable/collapsible contents of a details element.",
		Baseline:    Baseline{Status: "low", LowDate: "2025-09-16"},
	},
	{
		Name:        "file-selector-button",
		Description: "The ::file-selector-button CSS pseudo-element represents the button of an input of type=\"file\".",
		Baseline:    Baseline{Status: "high", LowDate: "2021-04-26", HighDate: "2023-10-26"},
	},
	{
		Name:        "first-letter",
		Description: "Represents the first letter of an element, if it is not preceded by any other content (such as images or inline tables) on its line.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "first-line",
		Description: "Describes the contents of the first formatted line of its originating element.",
		Baseline:    Baseline{Status: "high", LowDate: "2015-07-29", HighDate: "2018-01-29"},
	},
	{
		Name:        "grammar-error",
		Description: "The ::grammar-error CSS pseudo-element represents a text segment which the user agent has flagged as grammatically incorrect.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "highlight",
		Description: "The ::highlight() CSS pseudo-element applies styles to a custom highlight.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "marker",
		Description: "The ::marker CSS pseudo-element selects the marker box of a list item, which typically contains a bullet or number. It works on any element or pseudo-element set to display: list-item, such as the <li> and <summary> elements.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "part",
		Description: "The ::part CSS pseudo-element represents any element within a shadow tree that has a matching part attribute.",
		Baseline:    Baseline{Status: "high", LowDate: "2020-07-28", HighDate: "2023-01-28"},
	},
	{
		Name:        "picker",
		Description: "The ::picker() CSS pseudo-element targets the picker part of an element, for example the drop-down picker of a customizable select element.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "picker-icon",
		Description: "The ::picker-icon CSS pseudo-element targets the picker icon inside form controls that have an icon associated with them. In the case of a customizable select element, it selects the arrow icon shown on the <select> element that points down when it is closed.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "placeholder",
		Description: "The ::placeholder CSS pseudo-element represents the placeholder text of a form element.",
		Baseline:    Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name:        "scroll-marker",
		Description: "The ::scroll-marker CSS pseudo-element can be generated inside any element and represents its scroll marker. All elements can have a ::scroll-marker pseudo-element, which is placed into the ::scroll-marker-group of the nearest scroll container ancestor. A scroll marker behaves like an anchor (a element) whose scroll target is the marker's originating element — and scrolls the scroll container to that element when activated.",
		StatusInfo:  StatusInfo{Status: "experimental"},
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "scroll-marker-group",
		Description: "The ::scroll-marker-group CSS pseudo-element is generated inside a scroll container and contains any ::scroll-marker pseudo-elements generated on descendants of the scroll container.",
		StatusInfo:  StatusInfo{Status: "experimental"},
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "selection",
		Description: "Represents the portion of a document that has been highlighted by the user.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "shadow",
		Description: "Matches the shadow root if an element has a shadow tree.",
	},
	{
		Name:        "slotted",
		Description: "The ::slotted() CSS pseudo-element represents any element that has been placed into a slot inside an HTML template (see Using templates and slots for more information).",
		Baseline:    Baseline{Status: "high", LowDate: "2020-01-15", HighDate: "2022-07-15"},
	},
	{
		Name:        "spelling-error",
		Description: "The ::spelling-error CSS pseudo-element represents a text segment which the user agent has flagged as incorrectly spelled.",
		Baseline:    Baseline{Status: "false"},
	},
	{
		Name:        "target-text",
		Description: "The ::target-text CSS pseudo-element represents the text that has been scrolled to if the browser supports scroll-to-text fragments. It allows authors to choose how to highlight that section of text.",
		Baseline:    Baseline{Status: "low", LowDate: "2024-12-11"},
	},
	{
		Name:        "view-transition",
		Description: "The ::view-transition CSS pseudo-element represents the root of the view transitions overlay, which contains all view transitions and sits over the top of all other page content.",
		Baseline:    Baseline{Status: "low", LowDate: "2025-10-14"},
	},
	{
		Name:        "view-transition-group",
		Description: "The ::view-transition-group CSS pseudo-element represents a single view transition snapshot group.",
		Baseline:    Baseline{Status: "low", LowDate: "2025-10-14"},
	},
	{
		Name:        "view-transition-image-pair",
		Description: "The ::view-transition-image-pair CSS pseudo-element represents a container for a view transition's \"old\" and \"new\" view states — before and after the transition.",
		Baseline:    Baseline{Status: "low", LowDate: "2025-10-14"},
	},
	{
		Name:        "view-transition-new",
		Description: "The ::view-transition-new CSS pseudo-element represents the \"new\" view state of a view transition — a snapshot live representation of the state after the transition.",
		Baseline:    Baseline{Status: "low", LowDate: "2025-10-14"},
	},
	{
		Name:        "view-transition-old",
		Description: "The ::view-transition-old CSS pseudo-element represents the \"old\" view state of a view transition — a static snapshot of the old view, before the transition.",
		Baseline:    Baseline{Status: "low", LowDate: "2025-10-14"},
	},
}

var pseudoClassMap = buildPseudoClassMap()

func buildPseudoClassMap() map[string]PseudoClass {
	m := make(map[string]PseudoClass, len(PseudoClasses))
	for _, p := range PseudoClasses {
		m[p.Name] = p
	}
	return m
}

var pseudoElementMap = buildPseudoElementMap()

func buildPseudoElementMap() map[string]PseudoElement {
	m := make(map[string]PseudoElement, len(PseudoElements))
	for _, p := range PseudoElements {
		m[p.Name] = p
	}
	return m
}
